version: 2
jobs:
  build:
    working_directory: /home/ubuntu
    docker:
      - image: ubuntu:14.04
    environment:
        - ENV: CI
        - BLUB: "fiowj3 90ru34ir50leq23le0ß23läqwöeüp"
    steps:
      - run: apt update
      # to make circleCI tools work properly ---
      - run: apt install -y git ssh tar gzip ca-certificates
      # to make circleCI tools work properly ---
      - checkout
      - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts
      - run: uname -a;pwd;df -h; ls -al;id -a
      - run:
          name: Print the Current Time
          command: date
      - run:
          command: |
            set -xu
            echo $ENV
            echo $BLUB
            echo Running test
            mkdir -p /tmp/artifacts
            echo bb
            echo xx
            echo aaa > /tmp/artifacts/blub.txt
            ls -al /tmp/artifacts/blub.txt
      # Save artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
