version: 2
jobs:
  build:
    working_directory: /home/ubuntu
    docker:
      - image: ubuntu:14.04
         environment:
         ENV: CI
    steps:
      - checkout
      - run: uname -a;pwd;df -h; ls -al;id -a
      - run:
          name: Print the Current Time
          command: date
      - run:
          command: |
            echo Running test
            mkdir -p /tmp/artifacts
            echo bb
            echo xx
            echo aaa > /tmp/artifacts/blub.txt
      # Save artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
