version: 2
jobs:
  build:
    working_directory: /home/ubuntu
    docker:
      - image: circleci/classic:edge
         environment:
         ENV: CI
    steps:
      - checkout
      - run: uname -a;pwd;df -h; ls -al;id -a
      - run:
          name: Print the Current Time
          command: date
      - run:
          command: |
            echo Running test
            mkdir -p /tmp/test-results
            echo bb
            echo xx
